server:
  servlet:
    context-path: /mongo
  port: 27017

spring:
  data:
    mongodb:
      uri: mongodb://root:root@172.16.0.184:27017/mymongo
  mvc:
    throw-exception-if-no-handler-found: true
    resources:
      add-mappings: false
  datasource:
    url: jdbc:mysql://localhost:3306/altizure?useSSL=false&useUnicode=true&characterEncoding=utf-8&serverTimezone=UTC
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver